server {
        listen 80; //the server listens for http traffic on port 80
        server_name _;  //accept any hostname (wildcard)

        root /usr/share/nginx/html; //location where built files are stored (vite outputs dist/)
        index index.html; //file served by default when hitting /

        access_log /dev/stdout; //ecs/fargate monitoring works properly
        error_log /dev/stderr warn;

        # Optional - enable gzip compression - 50-80% smaller responses -> fast page loads
        gzip on;
        gzip_types text/plain text/css application/javascript application/json image/svg+xml;
        gzip_vary on;

        # SPA Routing - Route react router request correctly
        # important for refresh on nested routes or if user types path manually - without this setup, you will get 404
        location / {
            try_files $uri $uri/ /index.html; //if user types a path manually or refresh, it serves index.html instead and then react router takes over
          # Explanation of above line -
           # .$uri -> check if requested path exists as a file
           # .$uri -> Check if it's a folder
           # .index.html -> if not found, fallback to SPA entry index.html and then react router takes over
        }  

         # Optimized static assets - assets caching + immutable hashing - faster repeat visits, lower cdn cost
         # vite puts all compiled images, js, css etc into /assets. below block tells nginx, if file exists serve it. 
         # If not, return 404 (don't send index.html, because that would break assets) 
        location /assets/ {  
            try_files $uri =404;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # backend api reverse proxy (same domain)
        # location /api/ {
        #     proxy_pass http://mybakend:8080/; //update your backend service and port here
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }

        # # Strong security headers - more protection against common browser attacks
        # add_header X-Content-Type-Options "nosniff" always;
        # add_header X-Frame-Options "DENY" always;
        # add_header X-XSS-Protection "1; mode=block";
        # add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        # # add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
        # # add_header Cross-Origin-Opener-Policy "same-origin" always;
        # # add_header Cross-Origin-Embedder-Policy "require-corp" always;
        # # add_header Cross-Origin-Resource-Policy "same-origin" always;
        # # add_header Content-Security-Policy $csp_header always;
        # # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;


        
    }